### ISSUE TITLE
Not able to import table

### ISSUE THREAD

**Issue by aborruso** [calpaterson/csvbase#127]
# Description

# Steps to reproduce

1. choose to import a file
2. select it
3. run the import
4. have this error

![image](https://github.com/calpaterson/csvbase/assets/30607/f1d03b50-d488-4827-8469-a51d9af84e4e)

This is my input file

https://gist.github.com/aborruso/cbafecb2bea02b4c59e3270c85f19706

**Comment by calpaterson** [comment]
Hi Andrea,

I'm sorry that you ran into this problem.  The error page really should explain the problem, I will look into why it is not.

The problem is that the final column, `ultimo_fitto_mensile` has double decimal places in some lines: 1097 and 8727.

Does that help?

**Comment by aborruso** [comment]
I have corrected and it works. Thank you very much.

I don't know if it is possible to return the error to the user as well. Or in this case set everything to string. In any case it was my error

Thank you for all you do

**Comment by calpaterson** [comment]
> I have corrected and it works. Thank you very much.

Great, glad to hear it.

> I don't know if it is possible to return the error to the user as well. Or in this case set everything to string. In any case it was my error

I think both :)  I have done various bits of progress towards this, but have filed a master ticket here: https://github.com/calpaterson/csvbase/issues/128
