### ISSUE TITLE
Vary header

### ISSUE THREAD

**Issue by calpaterson** [calpaterson/csvbase#30]
# Description

# Steps to reproduce

1. Curl a page that is content negotiated, eg https://csvbase.com/meripaterson/stock-exchanges

# Expected result

A vary header set to indicate that `accept` was used

# Actual result

No vary header

# Additional details

https://news.ycombinator.com/item?id=34414610

**Comment by equirke** [comment]
![image](https://github.com/calpaterson/csvbase/assets/16085260/bcacc637-04b4-444a-bbf5-689f9f82165d)
This seems to have been fixed?

**Comment by calpaterson** [comment]
Agreed, long since fixed!
